# Generated by Django 4.1.2 on 2023-07-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='pass1',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='pass2',
            new_name='Retype_Password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='Username',
        ),
    ]
