# Generated by Django 4.1.2 on 2023-07-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_pass1_login_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Retype_Password',
            new_name='RetypePassword',
        ),
    ]
