# Generated by Django 4.1.2 on 2023-07-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_retype_password_login_retypepassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Password',
            new_name='CreatePassword',
        ),
    ]
